# Generated by Django 5.2.12 on 2026-04-06 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('net_height', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Mixed')], default='', max_length=2)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Mixed')], default='', max_length=2)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('levels', models.JSONField(blank=True, default=list)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volley_meetups.court')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('E', 'E'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('B+', 'B+'), ('A', 'A'), ('A+', 'A+'), ('S', 'S'), ('S+', 'S+')], default='', max_length=2)),
                ('content', models.TextField(blank=True, default='')),
                ('revisit_intention', models.CharField(blank=True, choices=[('Never', 'Never'), ('Maybe', 'Maybe'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volley_meetups.meetup')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('levels', models.JSONField(blank=True, default=list)),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volley_meetups.court')),
            ],
        ),
        migrations.AddField(
            model_name='meetup',
            name='seasonal_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volley_meetups.seasonalslot'),
        ),
    ]
